# -*- coding: utf-8 -*-
"""
Created on Mon Oct 23 19:03:42 2023

@author: Niruj
"""

import os    
import shutil
import time
import json
from selenium import webdriver
import pandas as pd


df = pd.read_csv("D:\LAND RA\python\data1.csv")

# Automating the pdf print using chrome's "save as pdf function"
# Define the printing options and profile
appState = {
    "recentDestinations": [
        {
            "id": "Save as PDF",
            "origin": "local",
            "account": ""
        }
    ],
    "selectedDestinationId": "Save as PDF",
    "version": 2
}
profile = {'printing.print_preview_sticky_settings.appState': json.dumps(appState)}

chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option('prefs', profile)
chrome_options.add_argument('--kiosk-printing')

# intialize driver
driver = webdriver.Chrome(options=chrome_options)


# Directory to save the PDF files
output_directory = "D:\\Land RA\pdf_files"  

# The URLs to the pdf can be generated by using the values from the columns 2,3 and 4 from already extracted data

# Iterate through the dataframe and print the URLs
for i in range(0,7916):
    p = df.iloc[i, 4]
    k = df.iloc[i, 2]
    v = df.iloc[i,3]

    while True:
        # Generate a filename using current row number
        filename = f"Bihar_Bhumi_{i}.pdf"
        file_path = os.path.join(output_directory, filename)

        # Check if the file already exists, if not, break the loop
        if not os.path.exists(file_path):
            break
    
    # Construct the new URL with the updated "v", "p" and "k" values
    url = f"https://emutation.bihar.gov.in/LRCRoRGistDemo/TransReg2Report.aspx?d=7&c=1&s=1&h=1&m=214/1&v={v}%20%20%20%20%20%20%20%20%20&p={p}&k={k}"

    driver.get(url)
    time.sleep(2)
    driver.execute_script(f'window.print("{file_path}");')

    # Move the downloaded file to a new name
    filename = max([output_directory + "\\" + f for f in os.listdir(output_directory)], key=os.path.getctime)
    shutil.move(filename, os.path.join(output_directory, f"newPDFName_{i}.pdf"))
    
    i = i +1
    
    
    

